#!/usr/bin/env sh

for spec in ../SPECS/*.spec; do
    sources=$(egrep '^Source[0-9]+:' "$spec" | egrep 'https?' | awk '{print $2}')
    if test -z "$sources"; then
        echo "No sources found in $spec" 1>&2
        exit 1
    fi
    echo "$sources" | while read source_url; do
        filename=$(expr "$source_url" : '.*\(/.\+\)')
        if test -z "$filename"; then
            echo "Failed to extract filename from $source_url. Aborting." 1>&2
            exit 1
        fi
        filename=${filename:1}
        if test -f "$filename"; then
            echo "$filename exists, skipping"
        else
            wget "$source_url"
        fi
    done
done

